project:
  type: book

book:
  title: "Ecuaciones Diferenciales"
  author: "Luis E. Mendoza"
  chapters:
    - index.qmd
    - intro.qmd
    - part: "Ecuaciones Diferenciales de Primer Orden"
      chapters:
        - separables.qmd
        - valiniciales.qmd
        - exactas.qmd
        - homogeneas.qmd
        - factint.qmd
        - ejerciciosdiv1.qmd
        - maximaEDO.qmd
    - part: "Ecuaciones Diferenciales de Orden Superior"
      chapters:
        - homogeneasSuperiores.qmd
        - noHomoSup.qmd
    - part: "Transformada de Laplace"
      chapters:
        - avanzando.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
    toc-title: Contenido
  pdf:
    documentclass: scrreprt
  epub:
    toc: true
    toc-title: Contenido
    html-math-method: mathml



