# Solución de EDO con un CAS

Tomemos como ejemplo la EDO:

$$
\frac{dy}{dx}=xy
$$

Sabemos que es una EDO separable, por lo que el procedimiento para resolverla es relativamente fácil:

$$
\frac{dy}{y}=x\ dx
$$

$$
\int{\frac{dy}{y}}=\int{x\ dx}
$$

$$
\mathrm{ln}|y|=\frac{x^2}{2}+C
$$

$$
y=C\cdot \exp{\left(\frac{x^2}{2}\right)}
$$

::: {.callout-note}
# Nota

Se ha escrito el número de Euler con su otra nomenclatura (exp) para facilitar su lectura.

:::

## Maxima

Ahora veamos cómo se resuelve utilizando el software CAS llamado Maxima. Introduzcamos la EDO anterior de manera que Maxima la reconozca.

```maxima
(%i1) 'diff(y,x)x*y;
```

Un diferencial se expresa con el comando `diff()`, con la variable dependiente primero y enseguida la independiente, separadas por una `,`. Sin embargo, se le agrega la tilde para evitar que Maxima trate de derivar lo que pongamos dentro del mismo. Por otro lado, la multiplicación se indica de manera usual (con un asterisco). El `;` es necesario para terminar la sentencia.

Maxima nos debe mostrar lo que "entendió", para así verificar que realmente es lo que quisimos decirle.

```maxima
                                   dy
(%o1)                              ── = x y
                                   dx
```

::: {.callout-note}
# Importante

En Maxima el cursor o *prompt* nos indica si la línea mostrada es una entrada o una salida. Las entradas comienzan como `(%in)`, donde `n` es el número de entrada. Cuando Maxima nos da un resultado, lo mostrará con `(%om)`, donde `m` es el número de salida.

:::

Ahora pidamos al software que calcule la solución general de esta expresión mediante el comando `ode2()`. El símbolo de porcentaje recupera la última expresión escrita, y se indica la dependiente y la independiente tal como se hizo anteriormente.

```maxima
(%i2) ode2(%,y,x);
```

Maxima nos debería mostrar el resultado así:

```maxima
                                         2
                                        x
                                        ──
                                        2
(%o2)                             y = %e   %c
```

Podemos observar que, salvo el orden, la solución dada es igual a la obtenida manualmente.

::: {.callout-note}
# Importante

En la salida, Maxima utiliza el símbolo `%` para indicar que son variables reservadas.

:::

## Octave

Antes de cualquier cosa, será necesario instalar el paquete `Symbolic`:

```octave
pkg install -forge symbolic
```

::: {.callout-note}
# Importante

Octave necesita que el sistema tenga instalado *Python* y su librería *sympy*. Instálelos antes de utilizar Octave.

:::

Enseguida cargamos lo recién instalado:

```octave
pkg load symbolic
```

Ahora procedemos a resolver la misma EDO. Primero declaramos las variables dependiente e independiente:

```octave
1> syms y(x)
```

::: {.callout-note}
# Nota

Octave utiliza también un *prompt* para indicar entradas y salidas, pero son diferentes a los de Maxima. Las entradas colocan un número seguido de `>`. Las salidas anteponen el nombre de la variable solicitada o, si no asignamos una variable, pondrá `ans`.

:::


Luego, definimos la EDO:

```octave
2> eqdif=diff(y,x,1)==x*y
```

Octave debería devolver:

```octave
eqdif = (sym)

  d
  ──(y(x)) = x⋅y(x)
  dx
```

Pedimos la solución de la EDO a Octave:

```octave
3> dsolve(eqdif)
```

Y nos debería arrojar:

```octave
ans = (sym)

       2
      x
      ──
      2
  C₁⋅ℯ
```



